---
# This role installs elasticsearch

- name: Clau GPG del repository elasticsearch
  rpm_key: state=present key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: Afegir repository elasticsearch
  copy: src=elasticsearch-2.x.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644


- name: Paquets a instal.lar
  yum: name={{ item }} state=present
  with_items:
      - java-1.7.0-openjdk
      - elasticsearch

- name: Create data directory
  file: name=/var/data/elasticsearch owner=elasticsearch state=directory

# Configurar elasticsearch
- name: config elasticsearch
  copy: src=elasticsearch.yml
        dest=/etc/elasticsearch/
        owner=elasticsearch group=elasticsearch mode=0644

- name: install kopf
  command: bin/plugin install lmenezes/elasticsearch-kopf
           chdir=/usr/share/elasticsearch
           creates=/usr/share/elasticsearch/plugins/kopf
  become: yes
  notify: restart elasticsearch

- name: Arrancada automatica de elasticsearch
  service: name=elasticsearch enabled=yes state=started
  notify: restart elasticsearch
